name:                coffer
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/serokell/coffer/
license:             BSD3
author:              Magic_RB
maintainer:          magic_rb@redalder.org
copyright:           2022 Serokell
category:            Command Line Tools
extra-source-files:
- README.md

dependencies:
  - base >= 4.14.3.0 && < 5
  - lens
  - generic-lens
  - text
  - bytestring
  - unordered-containers
  - aeson
  - mtl
  - hashable
  - polysemy
  - scientific
  - tomland
  - validation-selective
  - optparse-applicative
  - servant-client
  - servant-client-core
  - fmt

default-extensions:
  - BlockArguments
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveAnyClass
  - DerivingVia
  - OverloadedStrings
  - DerivingStrategies
  - DataKinds
  - FlexibleContexts
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiWayIf
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - ViewPatterns

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-name-shadowing
  - -Wno-missing-import-lists
  - -Wno-missing-export-lists
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-monomorphism-restriction
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations

library:
  source-dirs:      lib
  dependencies:
    - servant
    - http-client
    - http-client-tls
    - http-types
    - containers
    - megaparsec
    - time
    - time-compat
    - vector

executables:
  coffer:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - coffer

tests:
  doctests:
    source-dirs:      test
    main:             Doctests.hs
    ghc-options:
      - -threaded
    dependencies:
      - coffer
      - doctest-parallel
