name:                coffer
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/serokell/coffer/
license:             BSD3
author:              Magic_RB
maintainer:          magic_rb@redalder.org
copyright:           2022 Serokell
category:            Command Line Tools
extra-source-files:
- README.md

dependencies:
  - aeson
  - base >= 4.14.3.0 && < 5
  - bytestring
  - exceptions
  - fmt
  - generic-lens
  - hashable
  - lens
  - mtl
  - optparse-applicative
  - polysemy
  - scientific
  - servant-client
  - servant-client-core
  - servant-server
  - text
  - tomland
  - unordered-containers
  - validation-selective

default-extensions:
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-name-shadowing
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe
  - -freverse-errors

library:
  source-dirs:      lib
  dependencies:
    - servant
    - http-client
    - http-client-tls
    - http-types
    - containers
    - megaparsec
    - time
    - time-compat
    - vector
    - extra

executables:
  coffer:
    source-dirs:      app/cli
    main:             Main.hs
    dependencies:
      - coffer

  coffer-server:
    source-dirs:      app/server
    main:             Main.hs
    dependencies:
      - coffer
      - warp

tests:
  test:
    source-dirs:      test
    main:             Main.hs
    build-tools:      tasty-discover:tasty-discover
    ghc-options:
      - -threaded
    dependencies:
      - coffer
      - megaparsec
      - tasty
      - tasty-hunit
  doctests:
    source-dirs:      doctests
    main:             Doctests.hs
    ghc-options:
      - -threaded
    dependencies:
      - coffer
      - doctest-parallel
